wait("chrome_urlbar_53.png")
click(Pattern("chrome_urlbar_53.png").targetOffset(-100, 0))
paste("https://drive.google.com/open?id=1plUbt9FE1hY1fnOkdHg6WgGebge8mWxsH2PQiY1Tm0M")
type(Key.ENTER)
setAutoWaitTimeout(30)
wait(Pattern("gdoc.png").similar(0.80))
wait(Pattern("printer.png").similar(0.60), 60)
click(Pattern("printer.png").similar(0.60).targetOffset(50, 60))