wait("ff_urlbar.png")
click(Pattern("ff_urlbar.png").targetOffset(-100, 0))
paste("https://drive.google.com/open?id=1fTGfC2e5hD590gNChcolhOyXFBRV1O2zdfbVLU44Y84")
type(Key.ENTER)
setAutoWaitTimeout(30)
wait(Pattern("gdoc.png").similar(0.80))
wheel(Pattern("doc_content_left_top_page_region.png").similar(0.85), WHEEL_DOWN, 100)
sleep(2)
wheel(Pattern("doc_content_left_top_page_region.png").similar(0.85), WHEEL_UP, 100)