wait("chrome_urlbar_53.png")
click(Pattern("chrome_urlbar_53.png").targetOffset(-100, 0))
paste("https://www.amazon.com/")
type(Key.ENTER)
setAutoWaitTimeout(30)
wait(Pattern('www_amazon_com.png').similar(0.80), 60)
wheel(Pattern("www_amazon_com.png").similar(0.85).targetOffset(0, 150), WHEEL_DOWN, 100)
sleep(2)
wheel(Pattern("www_amazon_com.png").similar(0.85).targetOffset(0, 150), WHEEL_UP, 100)
