wait("chrome_urlbar_53.png")
click(Pattern("chrome_urlbar_53.png").targetOffset(-100, 0))
paste("https://www.bing.com/search?q=flowers")
type(Key.ENTER)
setAutoWaitTimeout(30)
wait(Pattern('www_bing_com.png').similar(0.80), 60)
