wait("ff_urlbar.png")
click(Pattern("ff_urlbar.png").targetOffset(-100, 0))
paste("http://www.ask.com/web?q=mozilla")
type(Key.ENTER)
setAutoWaitTimeout(30)
wait(Pattern('www_ask_com.png').similar(0.80), 60)
